- src/canvas/README.md
> FIZZ-67 - Updated the Canvas README

- .vscode/extensions.json
- .vscode/settings.json
This adds VS Code extension support for Apache file headers
> [FIZZ-80] Apache 2.0 file header support

- CONTRIBUTORS.md
- src/schoology-extractor/poetry.lock
- src/schoology-extractor/pyproject.toml
- src/schoology-extractor/schoology_extractor/api/request_client.py
- src/schoology-extractor/schoology_extractor/lms_filesystem.py
- src/schoology-extractor/schoology_extractor/main.py
- src/schoology-extractor/schoology_extractor/mapping/assignments.py
- src/schoology-extractor/schoology_extractor/mapping/constants.py
- src/schoology-extractor/schoology_extractor/schoology_extract_facade.py
- src/schoology-extractor/tests/api/test_request_client.py
- src/schoology-extractor/tests/mapping/test_assignments.py
- src/schoology-extractor/tests/test_lms_filesystem.py
- src/schoology-extractor/tests/test_schoology_extract_facade.py
* Maps the Schoology Assignments format to the Ed-Fi LMS UDM format
* Writes assignments to the correct directory, using datetime for the file name
* Opportunistically fix an oversight for the Users file: write to the correct directory, using datetime for the file name
> [FIZZ-102]

- src/schoology-extractor/schoology_extractor/main.py
- src/schoology-extractor/schoology_extractor/schoology_extract_facade.py
- src/schoology-extractor/tests/test_schoology_extract_facade.py
It was originally a change implemented by Stephen, I merged by accident so I created this PR to implement some changes from code review.
For testing it, you should set up your environment, following the instructions in the [readme file](https://github.com/Ed-Fi-Exchange-OSS/Ed-Fi-X-Fizz/blob/FIZZ-102-code-review/src/schoology-extractor/README.md) for the extractor. I can get you the .env file on slack in case you need it, just let me know if it is the case.
The test should consist on two steps:
* Making sure that by running `poetry run python .\schoology_extractor\main.py` you get the expected output according with the [AC for this story](https://tracker.ed-fi.org/browse/FIZZ-102).
* Making sure that by running `poetry run pytest`, all the test are passing.
After this, the PR can be …
> [FIZZ-102] Changes from code review

- CONTRIBUTORS.md
- src/schoology-extractor/poetry.lock
- src/schoology-extractor/pyproject.toml
- src/schoology-extractor/schoology_extractor/api/request_client.py
- src/schoology-extractor/schoology_extractor/lms_filesystem.py
- src/schoology-extractor/schoology_extractor/main.py
- src/schoology-extractor/schoology_extractor/mapping/assignments.py
- src/schoology-extractor/schoology_extractor/mapping/constants.py
- src/schoology-extractor/schoology_extractor/schoology_extract_facade.py
- src/schoology-extractor/tests/api/test_request_client.py
- src/schoology-extractor/tests/mapping/test_assignments.py
- src/schoology-extractor/tests/test_lms_filesystem.py
- src/schoology-extractor/tests/test_schoology_extract_facade.py
Contains code for FIZZ-102 and its review.
> [FIZZ-148] October branch

- src/schoology-extractor/data/.gitignore
- src/schoology-extractor/poetry.lock
- src/schoology-extractor/pyproject.toml
- src/schoology-extractor/schoology_extractor/api/request_client.py
- src/schoology-extractor/schoology_extractor/helpers/constants.py
- src/schoology-extractor/schoology_extractor/helpers/sync.py
- src/schoology-extractor/schoology_extractor/helpers/sync_column_types.py
- src/schoology-extractor/schoology_extractor/main.py
- src/schoology-extractor/schoology_extractor/mapping/assignments.py
- src/schoology-extractor/schoology_extractor/mapping/users.py
- src/schoology-extractor/schoology_extractor/schoology_extract_facade.py
- src/schoology-extractor/tests/helpers/test_sync.py
- src/schoology-extractor/tests/mapping/test_assignments.py
- src/schoology-extractor/tests/mapping/test_users.py
- src/schoology-extractor/tests/test_schoology_extract_facade.py
For testing, you should set up your environment, following the instructions in the [readme file](https://github.com/Ed-Fi-Exchange-OSS/Ed-Fi-X-Fizz/blob/FIZZ-124/src/schoology-extractor/README.md) for the extractor. I can get you the .env file on slack in case you need it, just let me know if it is the case.
After the review, the PR can be merged into main branch.
> [FIZZ-124] Synchronization process and Create / Last Modified Dates for the users file

- src/google-classroom-extractor/google_classroom_extractor/mapping/assignments.py
- src/google-classroom-extractor/tests/mapping/assignments/test_assignments.py
Ticket says name should be "LMSSectionSourceSystemIdentifier", but techdocs says "LMSSectionIdentifier".  Going with techdocs to start.
> [FIZZ-160] include LMSSectionIdentifier in UDM assignment output

- src/google-classroom-extractor/google_classroom_extractor/api/api_caller.py
- src/google-classroom-extractor/google_classroom_extractor/api/courses.py
- src/google-classroom-extractor/google_classroom_extractor/api/coursework.py
- src/google-classroom-extractor/google_classroom_extractor/api/students.py
- src/google-classroom-extractor/google_classroom_extractor/api/submissions.py
- src/google-classroom-extractor/google_classroom_extractor/api/teachers.py
- src/google-classroom-extractor/google_classroom_extractor/api/usage.py
- src/google-classroom-extractor/google_classroom_extractor/config.py
- src/google-classroom-extractor/google_classroom_extractor/csv_generation/write.py
- src/google-classroom-extractor/google_classroom_extractor/main.py
- src/google-classroom-extractor/tests/csv_generation/test_write.py
- src/schoology-extractor/schoology_extractor/helpers/export_data.py
- src/schoology-extractor/schoology_extractor/helpers/sync.py
- src/schoology-extractor/schoology_extractor/main.py
- src/schoology-extractor/schoology_extractor/schoology_extract_facade.py
- src/schoology-extractor/tests/test_schoology_extract_facade.py
While intended primarily for Google Classroom, I made a few opportunistic updates in Schoology to keep them aligned.
> [FIZZ-78] Logging improvements

- src/google-classroom-extractor/google_classroom_extractor/api/courses.py
- src/google-classroom-extractor/google_classroom_extractor/api/resource_sync.py
- src/google-classroom-extractor/tests/api/courses/test_courses_sync.py
A PR for the factoring out of sync/CreateDate/LastModifiedDate, the first step of FIZZ-91, to allow for others to pick up GC stories if they want.
> [FIZZ-91] factor out sync-specific code from courses

- src/google-classroom-extractor/.vscode/launch.json
- src/google-classroom-extractor/google_classroom_extractor/api/courses.py
- src/google-classroom-extractor/google_classroom_extractor/api/coursework.py
- src/google-classroom-extractor/google_classroom_extractor/api/resource_sync.py
- src/google-classroom-extractor/google_classroom_extractor/api/students.py
- src/google-classroom-extractor/google_classroom_extractor/api/submissions.py
- src/google-classroom-extractor/google_classroom_extractor/api/teachers.py
- src/google-classroom-extractor/tests/api/api_helper.py
- src/google-classroom-extractor/tests/api/courses/test_courses_sync.py
- src/google-classroom-extractor/tests/api/coursework/test_coursework_sync.py
- src/google-classroom-extractor/tests/api/students/test_students_sync.py
- src/google-classroom-extractor/tests/api/submissions/test_submissions_sync.py
- src/google-classroom-extractor/tests/api/teachers/test_teachers_sync.py
Google Classroom sync process is now a function that takes a DataFrame, list of identity columns on the DataFrame, resource name (only for sync table naming) and sync DB engine.  All sync db tables have six columns:
SourceId - A composite identity for the data
Json - The data serialized to JSON
Hash - A hash of the data
CreateDate - The date the data was first created in the sync db
LastModifiedDate - The date the data was last updated in the sync db
SyncNeeded - A flag used during sync processing
The function returns a new DataFrame with the columns of the given DataFrame plus CreateDate and LastModifiedDate columns from the sync process.
> [FIZZ-195] Modify Google Classroom sync process to be generic

- src/file-utils/.vscode/settings.json
- src/file-utils/edfi_lms_file_utils/file_reader.py
- src/file-utils/pyproject.toml
- src/lms-ds-loader/README.md
- src/lms-ds-loader/edfi_lms_ds_loader/df_to_db.py
- src/lms-ds-loader/edfi_lms_ds_loader/helpers/constants.py
- src/lms-ds-loader/edfi_lms_ds_loader/loader_facade.py
- src/lms-ds-loader/edfi_lms_ds_loader/migrator.py
- src/lms-ds-loader/edfi_lms_ds_loader/scripts/mssql/create_section_tables.sql
- src/lms-ds-loader/edfi_lms_ds_loader/scripts/mssql/create_user_tables.sql
- src/lms-ds-loader/edfi_lms_ds_loader/scripts/mssql/initialize_lms_database.sql
- src/lms-ds-loader/edfi_lms_ds_loader/sql_adapter.py
- src/lms-ds-loader/poetry.lock
- src/lms-ds-loader/pyproject.toml
- src/lms-ds-loader/tests/test_loader_facade.py
* Creates the Section table and paired staging table.
* Uploads the latest section file into the database.
* Corrects a bug with the User upload.
> [LMS-115] Load Section Files into LMS Database

- LICENSE
- NOTICES.md
- src/notebooks/poetry.lock
- src/notebooks/pyproject.toml
- src/notebooks/record_counts.ipynb
- src/schoology-extractor/README.md
- src/schoology-extractor/tests/data_generation/README.md
- src/schoology-extractor/tests/data_generation/__main__.py
- src/schoology-extractor/tests/data_generation/assignments.py
What's changed?
* Opportunistically, I made some copyright updates that just needed to happen.
* Changed the record count notebook to use the published utilities.
* Updated the sample data generation scripts so that I could easily generate more assignments.
> [LMS-228] Performance testing; copyright update

- src/schoology-extractor/edfi_schoology_extractor/__main__.py
- src/schoology-extractor/edfi_schoology_extractor/api/__init__.py
- src/schoology-extractor/edfi_schoology_extractor/api/paginated_result.py
- src/schoology-extractor/edfi_schoology_extractor/api/request_client.py
- src/schoology-extractor/edfi_schoology_extractor/mapping/discussion_replies.py
- src/schoology-extractor/edfi_schoology_extractor/mapping/section_updates.py
- src/schoology-extractor/edfi_schoology_extractor/schoology_extract_facade.py
- src/schoology-extractor/tests/api/test_paginated_result.py
- src/schoology-extractor/tests/api/test_request_client.py
- src/schoology-extractor/tests/data_generation/assignments.py
- src/schoology-extractor/tests/mapping/test_discussion_replies.py
- src/schoology-extractor/tests/test_schoology_extract_facade.py
Currently includes some LMS-237 commits, will fix once LMS-237 is merged to main
> [LMS-252] Schoology extractor issues with Session Activity

- docs/sample-out/section=2385758954/attendance-events/2020-09-17-15-04-23.csv
- docs/sample-out/users/2020-11-01-00-00-01.csv
- src/lms-ds-loader/README.md
- src/lms-ds-loader/edfi_lms_ds_loader/df_to_db.py
- src/lms-ds-loader/edfi_lms_ds_loader/mssql_lms_operations.py
- src/lms-ds-loader/edfi_lms_ds_loader/scripts/mssql/create_assignment_submission_tables.sql
- src/lms-ds-loader/edfi_lms_ds_loader/scripts/mssql/create_section_activity_tables.sql
- src/lms-ds-loader/edfi_lms_ds_loader/scripts/mssql/create_system_activity_tables.sql
- src/lms-ds-loader/tests/test_df_to_db.py
- src/lms-ds-loader/tests/test_mssql_lms_operations.py
Draft PR to show where this is at. I believe it to be complete, but LMS-256 "Loader not soft-deleting correctly" is blocking my confirmation.
> [LMS-112] Restore records that were soft-deleted

- src/canvas-extractor/tests/data_generation/data_remover/__main__.py
- src/schoology-extractor/data_generation/data_remover/__main__.py
> [LMS-267] Scripts for deleting hardcoded ranges of Schoology and Canvas

- extension/EdFi.Ods.Extensions.LMSX/LMS-Harmonizer/1080-lms-assignment.sql
- extension/EdFi.Ods.Extensions.LMSX/LMS-Harmonizer/1090-lms-assignment-submissions.sql
- src/lms-harmonizer/edfi_lms_harmonizer/harmonizer.py
- src/lms-harmonizer/edfi_lms_harmonizer/runner.py
- src/lms-harmonizer/tests/test_harmonizer.py
- src/lms-harmonizer/tests_integration_sql/mssql_loader.py
- src/lms-harmonizer/tests_integration_sql/procs/mssql/harmonize_assignment_submissions/test_lmsassignment_submissions.py
Create, update and delete of lmsx.AssignmentSubmissions based on what we find in lms.AssignmentSubmissions.
> [LMS-347] Harmonize assignment submissions

- src/sql-adapter/edfi_sql_adapter/sql_adapter.py
- src/sql-adapter/pyproject.toml
- src/sql-adapter/tests/test_sql_adapter.py
This is the first of at least two pull requests for this ticket
> [LMS-359] Support for encrypted connections in the SQL Adapter

- extension/Descriptors/SubmissionStatusDescriptor.xml
- extension/EdFi.Ods.Extensions.LMSX/LMS-Harmonizer/1090-lms-assignment-submissions.sql
- src/lms-harmonizer/tests_integration_sql/mssql_loader.py
- src/lms-harmonizer/tests_integration_sql/procs/mssql/harmonize_assignment_submissions/test_lmsassignment_submissions.py
The harmonizer will populate the lmsx.AssignmentSubmission table with submissions with status='Missing' to match the way other extractors handle the missing submissions.
> [LMS-354] Determine when a student assignment submission is PAST DUE for Schoology

- src/lms-ds-loader/.env.example
- src/lms-harmonizer/.env.example
- src/lms-harmonizer/README.md
- src/lms-harmonizer/edfi_lms_harmonizer/__main__.py
- src/lms-harmonizer/edfi_lms_harmonizer/harmonizer.py
- src/lms-harmonizer/edfi_lms_harmonizer/helpers/argparser.py
- src/lms-harmonizer/edfi_lms_harmonizer/migrator.py
- src/lms-harmonizer/edfi_lms_harmonizer/runner.py
- src/lms-harmonizer/edfi_lms_harmonizer/scripts/postgresql/0001_initialize_lms_database.sql
- src/lms-harmonizer/edfi_lms_harmonizer/scripts/postgresql/0002_harmonize_lmsuser_canvas.sql
- src/lms-harmonizer/edfi_lms_harmonizer/scripts/postgresql/0003_harmonize_lmsuser_schoology.sql
- src/lms-harmonizer/edfi_lms_harmonizer/scripts/postgresql/0004_harmonize_lmsuser_google-classroom.sql
- src/lms-harmonizer/edfi_lms_harmonizer/scripts/postgresql/0009_view_exceptions_LMSUser.sql
- src/lms-harmonizer/edfi_lms_harmonizer/sql_for_exceptions_report.py
- src/lms-harmonizer/tests/test_harmonizer.py
Working with Canvas. Will be easy to get the next two LMS's.
The program will error out on sections. However, I was able insert fake `lms.LMSUser` and `edfi.Student` and see that the `LMSUser`'s Ed-Fi ID was set successfully.
```sql
insert into edfi.student
(personaltitleprefix
,firstname
,middlename
,lastsurname
,generationcodesuffix
,maidenname
,birthdate
,birthcity
,birthstateabbreviationdescriptorid
,birthinternationalprovince
,birthcountrydescriptorid
,dateenteredus
,multiplebirthstatus
,birthsexdescriptorid
,citizenshipstatusdescriptorid
,studentuniqueid
,createdate
,lastmodifieddate
,id)
values
(NULL
,'FirstName'
,NULL
,'LastName'
,NULL
,NULL
,'2010-01-01 00:00:00'
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,NULL
,'{student_unique_id}'
,'2021-01-01 00:00:00'
,'2021-01-01 00:00:00' …
```
> [LMS-448] Support for Harmonizing Users in PostgreSQL

- .github/workflows/security-scan.yml
- .github/workflows/test-canvas.yml
- src/canvas-extractor/edfi_canvas_extractor/graphql/assignments.py
- src/canvas-extractor/edfi_canvas_extractor/graphql/extractor.py
- src/canvas-extractor/poetry.lock
Note that this pull request is into `LMS-470` - that is, it is a pull request _into_ a pull request.
1. I filled in a missing comment on a function, which helped me clarify what it is doing.
2. Removed an unused import that caused `flake8` to fail.
3. Took the opportunity to update all dependencies.
> PR Suggestions

- src/canvas-extractor/edfi_canvas_extractor/extract_graphql.py
Add the function and the call from run function, all the variables need it in memory.
> [LMS-495] Add section activities functionality

- src/canvas-extractor/edfi_canvas_extractor/graphql/extractor.py
Still working on testing this functionality to verify mapping into CSV files
> [LMS-308] Logic for no submissions
